name: 'DBT_ASSESSMENT'
version: '1.0'
profile: 'default'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  dbt_assessment:        # lowercase project/folder name
    +schema: PUBLIC      # the schema in Snowflake
    +materialized: table
