name: 'DBT_ASSESSMENT'   # Project name (just metadata)
version: '1.0'           # Project version (metadata)

model-paths: ["models"]  # Where your model SQL files live
target-path: "target"    # Where dbt builds compiled SQL and artifacts
clean-targets:
  - "target"
  - "dbt_modules"

models:
  DBT_ASSESSMENT:        # Match your database name
    +schema: PUBLIC      # Force all models into PUBLIC schema
    +materialized: incremental  # Use incremental by default
