name: 'DBT_ASSESSMENT'
version: '1.0'
profile: 'default'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  DBT_ASSESSMENT:   # MUST match project name exactly
    +schema: PUBLIC
    +materialized: table
